import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialMigration1646760691292 implements MigrationInterface {
    name = 'InitialMigration1646760691292'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "adminUser" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(50) NOT NULL, "password" character varying(128) NOT NULL, CONSTRAINT "UQ_58bd2b086488ba1ba90847a192e" UNIQUE ("username"), CONSTRAINT "PK_f155e50a944f2658dc1ccb477a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_notice" ("id" SERIAL NOT NULL, "ownerId" integer NOT NULL, "noticeUserId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "interestId" integer, CONSTRAINT "PK_1fa9968b4608730dc7f3543b2c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drop_in_notice" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "dropInId" integer, "interestId" integer, CONSTRAINT "PK_8e546283da398aa135afa95071a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "draft_notice" ("id" SERIAL NOT NULL, "ownerId" integer NOT NULL, "noticeUserId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "draftId" integer, "interestId" integer, CONSTRAINT "PK_4d87260be8ebed464c45a36a19a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "draft" ("id" SERIAL NOT NULL, "fileName" character varying NOT NULL, "filePath" character varying NOT NULL, "visualArray" text NOT NULL, "audioTime" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "teamId" integer, CONSTRAINT "PK_0b2b03d3f2c998450423648bc65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "interest" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "ownerId" integer, "default" boolean, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6619d627e204e0596968653011f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drop_in" ("id" SERIAL NOT NULL, "filePath" character varying NOT NULL, "conversationId" character varying, "fileName" character varying, "isRead" boolean, "lastMessageTs" character varying, "visualArray" text, "audioTime" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" integer, "recipientId" integer, "teamId" integer, CONSTRAINT "PK_af536e02df1234cb6b07f146b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "type" character varying, "status" character varying NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "ownerId" integer, "teamId" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "team" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "conversationId" character varying, "stripeSubscriptionId" character varying, "stripeCustomerId" character varying, "stripeSubscriptionStatus" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "ownerId" integer, "organizationId" integer, CONSTRAINT "UQ_eccedf2af1cd2395faa3d93d440" UNIQUE ("conversationId"), CONSTRAINT "UQ_701d92ae930514bdb48208fae52" UNIQUE ("stripeSubscriptionId"), CONSTRAINT "PK_f57d8293406df4af348402e4b74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "url" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "leaderId" integer, CONSTRAINT "REL_2b68595ea6ffccf04f9d73bd8d" UNIQUE ("leaderId"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "slack_profile" ("id" SERIAL NOT NULL, "slackUserId" character varying NOT NULL, "slackAccessToken" character varying NOT NULL, "slackBotAccessToken" character varying, "code" character varying NOT NULL, "teamName" character varying NOT NULL, "teamId" character varying NOT NULL, "channelName" character varying NOT NULL, "channelId" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "REL_5dd4eb72712e471bcedb3c45a6" UNIQUE ("userId"), CONSTRAINT "PK_5b2f0fd2e95bb8f9e5263553e6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invite" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "invitedId" integer, "inviterId" integer, CONSTRAINT "PK_fc9fa190e5a3c5d80604a4f63e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "auth0Id" character varying, "email" character varying NOT NULL, "firstName" character varying, "lastName" character varying, "imgUrl" character varying, "imgPath" character varying, "workTitle" character varying, "communicationPreferences" character varying, "isActivated" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roleId" integer, "organizationId" integer, "organizationLeadId" integer, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credit_card" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "zipCode" character varying NOT NULL, "last4" character varying NOT NULL, "expiration" character varying NOT NULL, "cardToken" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_97c08b6c8d5c1df81bf1a96c43e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recovery_password" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "newPasswordToken" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_e614931ec2e45c70f388ff75919" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "draft_interests_interest" ("draftId" integer NOT NULL, "interestId" integer NOT NULL, CONSTRAINT "PK_d07e92ec4c43a464f9eb4e2b487" PRIMARY KEY ("draftId", "interestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_941e06ebe794717a971ffd0716" ON "draft_interests_interest" ("draftId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf54a939637236fec7d700b6a1" ON "draft_interests_interest" ("interestId") `);
        await queryRunner.query(`CREATE TABLE "drop_in_interests_interest" ("dropInId" integer NOT NULL, "interestId" integer NOT NULL, CONSTRAINT "PK_3f5000165130010d2b5ccf05c83" PRIMARY KEY ("dropInId", "interestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1144f9ba2d962782f9accff232" ON "drop_in_interests_interest" ("dropInId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0cff529953e5e2bb78c74bea8" ON "drop_in_interests_interest" ("interestId") `);
        await queryRunner.query(`CREATE TABLE "user_team_leader_team" ("userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "PK_cc15d31443107523fafa41b8684" PRIMARY KEY ("userId", "teamId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b76ec7a0a38f0c450c4662719f" ON "user_team_leader_team" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a4ee6f082ddd418d3f6f3e690" ON "user_team_leader_team" ("teamId") `);
        await queryRunner.query(`CREATE TABLE "user_team_member_team" ("userId" integer NOT NULL, "teamId" integer NOT NULL, CONSTRAINT "PK_2266ef2b82a6ae31a3e7beea63d" PRIMARY KEY ("userId", "teamId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89bc0c75c6fcdb3b89d1bf99d0" ON "user_team_member_team" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_348eb95e8d1b980b388e7d6db7" ON "user_team_member_team" ("teamId") `);
        await queryRunner.query(`CREATE TABLE "user_interests_interest" ("userId" integer NOT NULL, "interestId" integer NOT NULL, CONSTRAINT "PK_d01761bfe3b04d617d57c4927a3" PRIMARY KEY ("userId", "interestId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5afca45962c04f51b2e91e0351" ON "user_interests_interest" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d52a2a3498ea0af1471fd20025" ON "user_interests_interest" ("interestId") `);
        await queryRunner.query(`ALTER TABLE "user_notice" ADD CONSTRAINT "FK_f8e41a3637b784107fc82a431b5" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notice" ADD CONSTRAINT "FK_8ac8c1f9577259f39677352a62b" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in_notice" ADD CONSTRAINT "FK_f67b1f48dcd099fb295ae4f6d3f" FOREIGN KEY ("dropInId") REFERENCES "drop_in"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in_notice" ADD CONSTRAINT "FK_59dd6945122ad554bebe4b2268a" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_notice" ADD CONSTRAINT "FK_9666e6c42c4c5d9e61cc9e7ee7b" FOREIGN KEY ("draftId") REFERENCES "draft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_notice" ADD CONSTRAINT "FK_1585d1dfeac3894909ec7db4e7d" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft" ADD CONSTRAINT "FK_90f3a5f14d665063bc5fed6ecb0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft" ADD CONSTRAINT "FK_12c3ab7e98fec003e18aa3bf58f" FOREIGN KEY ("teamId") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in" ADD CONSTRAINT "FK_00b1c1dd7e4bac3bb04d9f37c4a" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in" ADD CONSTRAINT "FK_3204b8dfb2c18f0062ec6360a74" FOREIGN KEY ("recipientId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in" ADD CONSTRAINT "FK_3d407705bc1b9dcbc9f0c9ec971" FOREIGN KEY ("teamId") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315eb974b73391fb1c81b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_274f7f52fe174d6f3f857ab420a" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_db48ead85f05ccdd43d4e233f7c" FOREIGN KEY ("teamId") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team" ADD CONSTRAINT "FK_49a22109d0b97611c07768e37f1" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team" ADD CONSTRAINT "FK_12e10686074dba7e8fd02f41bf4" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_2b68595ea6ffccf04f9d73bd8dd" FOREIGN KEY ("leaderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slack_profile" ADD CONSTRAINT "FK_5dd4eb72712e471bcedb3c45a68" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_0297f3dcdd3250c964d84858b2b" FOREIGN KEY ("invitedId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invite" ADD CONSTRAINT "FK_1bfcd5d4cb51bf86c2e36f3da5e" FOREIGN KEY ("inviterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_dfda472c0af7812401e592b6a61" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_b73d9670d4c26b3aa7a6e9aae28" FOREIGN KEY ("organizationLeadId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_card" ADD CONSTRAINT "FK_5af060e164a7e2764ed1b15589d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "draft_interests_interest" ADD CONSTRAINT "FK_941e06ebe794717a971ffd07169" FOREIGN KEY ("draftId") REFERENCES "draft"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "draft_interests_interest" ADD CONSTRAINT "FK_cf54a939637236fec7d700b6a1b" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drop_in_interests_interest" ADD CONSTRAINT "FK_1144f9ba2d962782f9accff232f" FOREIGN KEY ("dropInId") REFERENCES "drop_in"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "drop_in_interests_interest" ADD CONSTRAINT "FK_f0cff529953e5e2bb78c74bea83" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team_leader_team" ADD CONSTRAINT "FK_b76ec7a0a38f0c450c4662719fc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_team_leader_team" ADD CONSTRAINT "FK_6a4ee6f082ddd418d3f6f3e690c" FOREIGN KEY ("teamId") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_team_member_team" ADD CONSTRAINT "FK_89bc0c75c6fcdb3b89d1bf99d0b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_team_member_team" ADD CONSTRAINT "FK_348eb95e8d1b980b388e7d6db7a" FOREIGN KEY ("teamId") REFERENCES "team"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_interests_interest" ADD CONSTRAINT "FK_5afca45962c04f51b2e91e03516" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_interests_interest" ADD CONSTRAINT "FK_d52a2a3498ea0af1471fd200251" FOREIGN KEY ("interestId") REFERENCES "interest"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_interests_interest" DROP CONSTRAINT "FK_d52a2a3498ea0af1471fd200251"`);
        await queryRunner.query(`ALTER TABLE "user_interests_interest" DROP CONSTRAINT "FK_5afca45962c04f51b2e91e03516"`);
        await queryRunner.query(`ALTER TABLE "user_team_member_team" DROP CONSTRAINT "FK_348eb95e8d1b980b388e7d6db7a"`);
        await queryRunner.query(`ALTER TABLE "user_team_member_team" DROP CONSTRAINT "FK_89bc0c75c6fcdb3b89d1bf99d0b"`);
        await queryRunner.query(`ALTER TABLE "user_team_leader_team" DROP CONSTRAINT "FK_6a4ee6f082ddd418d3f6f3e690c"`);
        await queryRunner.query(`ALTER TABLE "user_team_leader_team" DROP CONSTRAINT "FK_b76ec7a0a38f0c450c4662719fc"`);
        await queryRunner.query(`ALTER TABLE "drop_in_interests_interest" DROP CONSTRAINT "FK_f0cff529953e5e2bb78c74bea83"`);
        await queryRunner.query(`ALTER TABLE "drop_in_interests_interest" DROP CONSTRAINT "FK_1144f9ba2d962782f9accff232f"`);
        await queryRunner.query(`ALTER TABLE "draft_interests_interest" DROP CONSTRAINT "FK_cf54a939637236fec7d700b6a1b"`);
        await queryRunner.query(`ALTER TABLE "draft_interests_interest" DROP CONSTRAINT "FK_941e06ebe794717a971ffd07169"`);
        await queryRunner.query(`ALTER TABLE "credit_card" DROP CONSTRAINT "FK_5af060e164a7e2764ed1b15589d"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_b73d9670d4c26b3aa7a6e9aae28"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_dfda472c0af7812401e592b6a61"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_1bfcd5d4cb51bf86c2e36f3da5e"`);
        await queryRunner.query(`ALTER TABLE "invite" DROP CONSTRAINT "FK_0297f3dcdd3250c964d84858b2b"`);
        await queryRunner.query(`ALTER TABLE "slack_profile" DROP CONSTRAINT "FK_5dd4eb72712e471bcedb3c45a68"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_2b68595ea6ffccf04f9d73bd8dd"`);
        await queryRunner.query(`ALTER TABLE "team" DROP CONSTRAINT "FK_12e10686074dba7e8fd02f41bf4"`);
        await queryRunner.query(`ALTER TABLE "team" DROP CONSTRAINT "FK_49a22109d0b97611c07768e37f1"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_db48ead85f05ccdd43d4e233f7c"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_274f7f52fe174d6f3f857ab420a"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315eb974b73391fb1c81b"`);
        await queryRunner.query(`ALTER TABLE "drop_in" DROP CONSTRAINT "FK_3d407705bc1b9dcbc9f0c9ec971"`);
        await queryRunner.query(`ALTER TABLE "drop_in" DROP CONSTRAINT "FK_3204b8dfb2c18f0062ec6360a74"`);
        await queryRunner.query(`ALTER TABLE "drop_in" DROP CONSTRAINT "FK_00b1c1dd7e4bac3bb04d9f37c4a"`);
        await queryRunner.query(`ALTER TABLE "draft" DROP CONSTRAINT "FK_12c3ab7e98fec003e18aa3bf58f"`);
        await queryRunner.query(`ALTER TABLE "draft" DROP CONSTRAINT "FK_90f3a5f14d665063bc5fed6ecb0"`);
        await queryRunner.query(`ALTER TABLE "draft_notice" DROP CONSTRAINT "FK_1585d1dfeac3894909ec7db4e7d"`);
        await queryRunner.query(`ALTER TABLE "draft_notice" DROP CONSTRAINT "FK_9666e6c42c4c5d9e61cc9e7ee7b"`);
        await queryRunner.query(`ALTER TABLE "drop_in_notice" DROP CONSTRAINT "FK_59dd6945122ad554bebe4b2268a"`);
        await queryRunner.query(`ALTER TABLE "drop_in_notice" DROP CONSTRAINT "FK_f67b1f48dcd099fb295ae4f6d3f"`);
        await queryRunner.query(`ALTER TABLE "user_notice" DROP CONSTRAINT "FK_8ac8c1f9577259f39677352a62b"`);
        await queryRunner.query(`ALTER TABLE "user_notice" DROP CONSTRAINT "FK_f8e41a3637b784107fc82a431b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d52a2a3498ea0af1471fd20025"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5afca45962c04f51b2e91e0351"`);
        await queryRunner.query(`DROP TABLE "user_interests_interest"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_348eb95e8d1b980b388e7d6db7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89bc0c75c6fcdb3b89d1bf99d0"`);
        await queryRunner.query(`DROP TABLE "user_team_member_team"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a4ee6f082ddd418d3f6f3e690"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b76ec7a0a38f0c450c4662719f"`);
        await queryRunner.query(`DROP TABLE "user_team_leader_team"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0cff529953e5e2bb78c74bea8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1144f9ba2d962782f9accff232"`);
        await queryRunner.query(`DROP TABLE "drop_in_interests_interest"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf54a939637236fec7d700b6a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_941e06ebe794717a971ffd0716"`);
        await queryRunner.query(`DROP TABLE "draft_interests_interest"`);
        await queryRunner.query(`DROP TABLE "recovery_password"`);
        await queryRunner.query(`DROP TABLE "credit_card"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "invite"`);
        await queryRunner.query(`DROP TABLE "slack_profile"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "team"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "drop_in"`);
        await queryRunner.query(`DROP TABLE "interest"`);
        await queryRunner.query(`DROP TABLE "draft"`);
        await queryRunner.query(`DROP TABLE "draft_notice"`);
        await queryRunner.query(`DROP TABLE "drop_in_notice"`);
        await queryRunner.query(`DROP TABLE "user_notice"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "adminUser"`);
    }

}
